//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<int> NumberOfBag { get; set; }
        public Nullable<System.DateTime> BloodNeededDate { get; set; }
        public string ContactNumber { get; set; }
        public string WhyBloodNeeded { get; set; }
        public string BlooddonationAddress { get; set; }
    
        public virtual BloodGroup BloodGroup1 { get; set; }
    }
}
